/*
 * CHANGED:
 * Datatype of borrower from String to Schema.Types.ObjectId
 * Datatype of lender from String to Schema.Types.ObjectId
 * Schema.Types.ObjectId is the strange ObjectId that Mongo generates
 * 
 * 
 */

var bcrypt = require('bcrypt-nodejs');
var crypto = require('crypto');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var productSchema = new mongoose.Schema({
    name: String,
    borrower: {type: Schema.Types.ObjectId, ref: 'User'}, //THIS SHOULD BE THE _ID GENERATED BY MONGO
    lender: {type: Schema.Types.ObjectId, ref: 'User'}, //THIS SHOULD BE THE _ID GENERATED BY MONGO 
    description: String,
    productid_id: Number,
    imgUrl: String,
    price: Number,
    isBorrowed: Boolean
});


module.exports = mongoose.model('Product', productSchema);
